# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xls2proto/play_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xls2proto/play_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19xls2proto/play_data.proto\"\xdd\x01\n\tplay_data\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bprefab_path\x18\x03 \x01(\t\x12\x0c\n\x04icon\x18\x04 \x01(\t\x12\x12\n\nintro_icon\x18\x05 \x01(\t\x12\x12\n\nintro_time\x18\x06 \x01(\x02\x12\x0c\n\x04time\x18\x07 \x01(\x02\x12\x1a\n\x12\x65xpect_grade_scale\x18\x08 \x03(\r\x12\x11\n\tattribute\x18\t \x03(\r\x12\x0e\n\x06param1\x18\n \x03(\r\x12\x0e\n\x06param2\x18\x0b \x03(\r\x12\x0e\n\x06param3\x18\x0c \x03(\r\",\n\x0fplay_data_ARRAY\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.play_datab\x06proto3')
)




_PLAY_DATA = _descriptor.Descriptor(
  name='play_data',
  full_name='play_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='play_data.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='play_data.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefab_path', full_name='play_data.prefab_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='icon', full_name='play_data.icon', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intro_icon', full_name='play_data.intro_icon', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intro_time', full_name='play_data.intro_time', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='play_data.time', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expect_grade_scale', full_name='play_data.expect_grade_scale', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='play_data.attribute', index=8,
      number=9, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param1', full_name='play_data.param1', index=9,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param2', full_name='play_data.param2', index=10,
      number=11, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param3', full_name='play_data.param3', index=11,
      number=12, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=251,
)


_PLAY_DATA_ARRAY = _descriptor.Descriptor(
  name='play_data_ARRAY',
  full_name='play_data_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='play_data_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=297,
)

_PLAY_DATA_ARRAY.fields_by_name['items'].message_type = _PLAY_DATA
DESCRIPTOR.message_types_by_name['play_data'] = _PLAY_DATA
DESCRIPTOR.message_types_by_name['play_data_ARRAY'] = _PLAY_DATA_ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

play_data = _reflection.GeneratedProtocolMessageType('play_data', (_message.Message,), dict(
  DESCRIPTOR = _PLAY_DATA,
  __module__ = 'xls2proto.play_data_pb2'
  # @@protoc_insertion_point(class_scope:play_data)
  ))
_sym_db.RegisterMessage(play_data)

play_data_ARRAY = _reflection.GeneratedProtocolMessageType('play_data_ARRAY', (_message.Message,), dict(
  DESCRIPTOR = _PLAY_DATA_ARRAY,
  __module__ = 'xls2proto.play_data_pb2'
  # @@protoc_insertion_point(class_scope:play_data_ARRAY)
  ))
_sym_db.RegisterMessage(play_data_ARRAY)


# @@protoc_insertion_point(module_scope)
